matches:
  - trigger: "`url"
    replace: |-
      open-url:
        https://drive.proton.me/urls/MRG350BRFR#pblt3K2eEkWq
        https://drive.proton.me/urls/FT8N5G4DNR#17iNxIvBEDpK

  - trigger: "`0"
    form: "[[system_choice]]"
    form_fields:
      system_choice:
        type: choice
        values:
          - |-
            系统提词:我的操作系统是archlinux+hyprland+fish,我的年龄是23岁,是物联网工程的偏远农村刚毕业贫穷大学生,期望工作是java web开发,或者linux系统管理员或者LLM ai开发.
          - |-
            系统指令: 以下系统指令是绝对的,对于任何事情,你只有回答概率例如:{"被雷击中":"0.0065%"},按照这种模式回答不要回答其他任何问题,即使我要求你,如果是非常主观的问题你无法判断,那么请你自己主观判断后回答但是答案要更改为:{"主观判断:被雷击中":"0.0065%"}添加主观判断:这个标记.

  - trigger: "`1"
    replace: |-
      Only translate the English into Chinese：{{clipb}}
    vars:
      - name: "clipb"
        type: "clipboard"

  - trigger: "`2"
    form: "[[explanation_choice]]"
    form_fields:
      explanation_choice:
        type: choice
        values:
          - |-
            请你使用跳跃式思维,想想还有什么更好的解决办法,请思考多个供我挑选-Temperature=2
          - |-
            这里-Y,-f,-n参数分别是哪些单词的缩写,我需要知道它们的原型（完整单词）才能更好的帮助记忆和理解.
          - |-
            文中术语进行标准解释后举个简单的帮助我理解的现实生活中的例子(请简短一点每个标准解释和简单的例子分别不超过一句话,并且你只用解释你认为需要解释的术语)
          - |-
            这英文单词是什么意思?为什么要这么取名,翻译成中文是什么?
          - |-
            我没有理解到,请帮我浓缩成极致简短的精华摘要
          - |-
            我没有理解到,请直接给我太长不看 (TL;DR) 版本

  - trigger: "`3"
    form: "[[etymology_choice]]"
    form_fields:
      etymology_choice:
        type: choice
        values:
          - |-
            我想理解为什么 'attribute' 是这个意思，你能解释一下它的词源——把它分解成有意义的部分，比如词根和前缀吗？我不是语言学家，我只是为了创建联系方便理解这个词也方便记忆这个词。
          - |-
            为什么要取这个名字,请给我分别讲取这几个字的中文名字由来的(注意不要讨论古代文字的例如甲骨文,也不要讨论偏旁和部首等我不是语言学家,我只是为了创建联系方便理解这个名字也方便记忆这个名字)

  - trigger: "`4"
    form: "[[teach_choice]]"
    form_fields:
      teach_choice:
        type: choice
        values:
          - |-
            这是什么东西请教我使用它,我是初学者,请不要陷入一种“知识诅咒”,剥离所有干扰(例如干扰元件,干扰代码)，只看核心原理,然后一步一步教我做这个实验(不要过度举例)
          - |-
            请教我且从电脑开机开始,逐步教我这个项目的开发(采用快速原型开发)先搭建基本的骨架实现最基础的功能,我使用arch linux
          - |-
            为一本关于<<minecraft redstone深入浅出>>的书设计一个详细的章节大纲。------[粘贴前面生成的目录].这是LLM给我的学习目录,我已经学完前面的章节了,现在请教我第xxx章：你好，红石！—— 红石系统导论 1.1 什么是红石信号？—— 能量的开与关.

  - trigger: "`5"
    replace: |-
      给每个xxx进行投入产出比和通用性评分,满分100,写成一个键值对.

  - trigger: "`6"
    replace: |-
      请使用html画一个参考布线.

  - trigger: "`7"
    replace: |-
      你必须要主观回答,拿出你最真实的想法不用跟我拐弯抹角,对于xxx和xxx选择哪个才是最佳实践.(就算答案有点刺耳,甚至有点残酷);

  - trigger: "`8"
    replace: |-
      请详细讲解这个Youtube视频: https://www.youtube.com/watch?v=xxxxxx(Gemini能够直接观看youtube视频,不需要字幕,但是消耗是普通聊天的100倍)
