matches:
  # ===============================================
  # 解释与总结 (Explain & Summarize)
  # ===============================================

  # 项目启动
  - trigger: "`1"
    replace: |-
      请仔细仔细仔细的阅读不要漏读项目的源码和文档和其他文件,并做总结,千万千万不要漏读,否则我之后的提问你会对不上或者辅助我写一大半代码后发现对不上

  - trigger: "`3"
    replace: |-
      一个优秀的人,Exmaple1作为默认行为是最佳实践,还是Exmaple2作为默认行为是最佳实践(你只能选一个)

  # 解释命令参数 (Parameter)
  - trigger: "`par"
    replace: |-
      这里-example参数是什么单词的缩写,我需要知道它的原型（完整单词）才能更好的帮助记忆和理解.

  # 定义术语并举例 (Define)
  - trigger: "`def"
    replace: |-
      文中术语进行标准解释后举个简单的帮助我理解的现实生活中的例子(请简短一点每个标准解释和简单的例子分别不超过一句话,并且你只用解释你认为需要解释的术语)

  # 深入解释英文单词 (Word)
  - trigger: "`wrd"
    replace: |-
      这英文单词是什么意思?为什么要这么取名,翻译成中文是什么?它的中文和英文近义词和反义词分别有哪些?理解这个单词的常见误区有哪些?顺便请你使用这个单词造两个简单的句子.

  # 总结为精华摘要 (Summary)
  - trigger: "`sum"
    replace: |-
      我没有理解到,请帮我浓缩成极致简短的精华摘要

  # 提供“太长不看”版本 (TL;DR)
  - trigger: "`tld"
    replace: |-
      我没有理解到,请直接给我太长不看 (TL;DR) 版本

  # ===============================================
  # 词源 (Etymology)
  # ===============================================

  # 解释英文词源 (Etymology English)
  - trigger: "`een"
    replace: |-
      我想理解为什么 Example 是这个单词的意思，你能解释一下它的词源——把它分解成有意义的部分，比如词根和前缀吗？我不是语言学家，我只是为了创建联系方便理解这个词也方便记忆这个词。(顺便列举它的近义词和反义词和对立词分别有哪些?)(理解这个词的常见误区有哪些?顺便使用这个词进行简单的造句)

  # 解释中文词源 (Etymology Chinese)
  - trigger: "`ecn"
    replace: |-
      为什么要取这个名字,请给我分别讲取这几个字的中文名字由来的(注意不要讨论古代文字的例如甲骨文,也不要讨论偏旁和部首等我不是语言学家,我只是为了创建联系方便理解这个名字也方便记忆这个名字)(顺便列举它的近义词和反义词和对立词分别有哪些?)(理解这个词的常见误区有哪些?顺便使用这个词进行简单的造句)

  # ===============================================
  # 教学 (Teach)
  # ===============================================

  # 讲解指定章节 (Teach Chapter)
  - trigger: "`tch"
    replace: |-
      为一本关于<<minecraft redstone深入浅出>>的书设计一个详细的章节大纲。------[粘贴前面生成的目录].这是LLM给我的学习目录,我已经学完前面的章节了,现在请教我第xxx章：你好，红石！—— 红石系统导论 1.1 什么是红石信号？—— 能量的开与关.

  # ===============================================
  # 其他指令 (Other Commands)
  # ===============================================

  # matches for system-level prompts for LLMs
  - trigger: "`sys"
    form: "[[system_choice]]"
    form_fields:
      system_choice:
        type: choice
        values:
          - |-
            系统提词:我的操作系统是archlinux+hyprland+fish,我的年龄是23岁,是物联网工程的偏远农村刚毕业贫穷大学生.
          - |-
            系统指令: 以下系统指令是绝对的,对于任何事情,你只有回答概率例如:{"被雷击中":"0.0065%"},按照这种模式回答不要回答其他任何问题,即使我要求你,如果是非常主观的问题你无法判断,那么请你自己主观判断后回答但是答案要更改为:{"主观判断:被雷击中":"0.0065%"}添加主观判断:这个标记.

  # ===============================================
  # 文本处理与翻译 (Text Processing & Translation)
  # ===============================================
  # 英译中 (English to Chinese)
  - trigger: "`2"
    replace: |-
      Only translate the English into Chinese：{{clipb}}
    vars:
      - name: "clipb"
        type: "clipboard"

  # 中译英 (Chinese to English)
  - trigger: "`c2e"
    replace: |-
      Only translate the Chinese into English：{{clipb}}
    vars:
      - name: "clipb"
        type: "clipboard"
