# ~/.config/starship.toml

# 不在命令前添加空行，保持紧凑
add_newline = false

# [核心格式] - 将 $directory 移动到末尾，$character 之前
format = """
$username@$hostname \
FishNvimHyprland(magenta bold)\
[($git_branch$git_status)](yellow)\
$rust\
$golang\
$java\
$python\
$nodejs\
$php\
$ruby\
$c\
$elixir\
$kotlin\
$docker_context\
$directory\
$character"""

# --- 用户名和主机名 ---

[username]
show_always = true
style_user = "yellow bold"
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "green bold"
trim_at = "."

# --- 目录路径 ---

[directory]
style = "blue"
format = " [$path]($style)"
truncate_to_repo = false
truncation_length = 0
home_symbol = "~"

# --- Git 相关模块 ---

[git_branch]
symbol = ""
format = " $branch"
style = "cyan bold"

[git_status]
format = "$all_status$ahead_behind"
style = "red bold"
ahead = " Ah"
behind = " Bh"
diverged = " Dv"
conflicted = " Cf"
deleted = " Dl"
renamed = " Rn"
modified = " Md"
staged = " St"
untracked = " Un"
stashed = " Sh"

# --- 编程语言模块 ---

[rust]
symbol = ""
format = " ($version)"
style = "bright-cyan bold"

[golang]
symbol = ""
format = " (Go $version)"
style = "bright-cyan bold"

[java]
symbol = ""
format = " (Java $version)"
style = "bright-cyan bold"

# --- Python 模块（已更新）---
[python]
symbol = ""
# 当虚拟环境激活时，会显示类似 (venv-name Py 3.x.x) 的格式
format = " ($virtualenv $version)"
style = "bright-cyan bold"

# --- 新增的编程语言模块 ---

[nodejs]
symbol = ""
format = " (Node $version)"
style = "bright-green bold"

[php]
symbol = ""
format = " (PHP $version)"
style = "bright-purple bold"

[ruby]
symbol = ""
format = " (Ruby $version)"
style = "bright-red bold"

[c]
symbol = ""
format = " (C $version)"
style = "bright-yellow bold"

[elixir]
symbol = ""
format = " (Elixir $version)"
style = "bright-magenta bold"

[kotlin]
symbol = ""
format = " (Kotlin $version)"
style = "bright-blue bold"

# --- 其他模块 ---

[docker_context]
symbol = ""
format = " (Docker $context)"
style = "bright-cyan bold"

# --- 命令行结束符 ---

[character]
success_symbol = "[ >](green)"
error_symbol = "[ >](red)"
