customCommands:
  - key: 'c'
    # 修改这里的 date 命令格式
    command: "git commit -m \"$(date +'%Y-%m-%d %H:%M:%S'): {{.Form.CommitMessage}}\""
    context: 'files'
    prompts:
      - type: 'input'
        title: 'Commit message'
        key: 'CommitMessage'
    description: 'commit with date and time'
